apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: agent_prometheus_metrics
  displayName: Agent Metrics
  icon: /icons/destinations/otlp.svg
  description: Collect metrics from Prometheus exporters.
spec:
  version: 0.0.1
  supported_platforms:
    - macos
    - linux
    - windows
  parameters:
    - name: job_name
      label: Job Name
      description: The name of the scraper job. Will be set as service.name resource label.
      type: string
      default: "observiq-otel-collector"
      required: true

    - name: collection_interval
      label: Collection Interval
      description: How often (seconds) to scrape for metrics.
      type: int
      default: 60
      advancedConfig: true

  metrics:
    receivers: |
      - prometheus:
          config:
            scrape_configs:
              - job_name: '{{ .job_name }}'
                scrape_interval: {{ .collection_interval }}s
                static_configs:
                  - targets: ['0.0.0.0:8888']
